# Generated by Django 4.2.4 on 2023-09-15 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BallotCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ballot_confirmation_code",
                    models.CharField(default="N/A", max_length=30),
                ),
                (
                    "cast_vote",
                    models.CharField(
                        blank=True,
                        choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                        max_length=1,
                    ),
                ),
                ("creation_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ElectionConfirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirm_check",
                    models.BooleanField(
                        default=False,
                        help_text="Hereby, I confirm that the submitted election information is legit and correct.",
                    ),
                ),
                (
                    "agreement_check",
                    models.BooleanField(
                        default=False,
                        help_text="Hereby, I accept and sign the License Agreement of Unio voting application.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginWithLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VoterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("s", "signup"),
                            ("l", "login"),
                            ("o", "logout"),
                            ("v", "vote"),
                            ("y", "verify"),
                            ("x", "Reserved"),
                        ],
                        help_text="Voter Action Type",
                        max_length=1,
                    ),
                ),
                ("metadata", models.CharField(max_length=200)),
                ("action_datetime", models.DateTimeField()),
                (
                    "voter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballot_id", models.CharField(default="N/A", max_length=30)),
                ("confirmation_code", models.CharField(default="N/A", max_length=30)),
                (
                    "organizational_id",
                    models.CharField(blank=True, default="N/A", max_length=30),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="N/A", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="N/A", max_length=50),
                ),
                ("email", models.CharField(blank=True, default="N/A", max_length=50)),
                (
                    "vote",
                    models.CharField(
                        blank=True,
                        choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("question_1", models.CharField(default="N/A", max_length=200)),
                ("question_2", models.CharField(default="N/A", max_length=200)),
                ("creation_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("p", "pre-registration"),
                            ("r", "registration"),
                            ("n", "notice"),
                            ("v", "voting"),
                            ("y", "verification"),
                            ("t", "tally"),
                            ("o", "post-tally"),
                            ("x", "Reserved"),
                        ],
                        default="p",
                        help_text="Event Type",
                        max_length=1,
                    ),
                ),
                (
                    "notice_interval_hours",
                    models.IntegerField(
                        blank=True,
                        default=24,
                        validators=[django.core.validators.MinValueValidator(24)],
                    ),
                ),
                (
                    "voting_start_datetime",
                    models.DateTimeField(blank=True, default="0000-00-00 00:00"),
                ),
                (
                    "voting_end_datetime",
                    models.DateTimeField(blank=True, default="0000-00-00 00:00"),
                ),
                ("results_pie", models.ImageField(blank=True, upload_to="pics")),
            ],
            options={
                "unique_together": {("name", "question_1", "question_2")},
            },
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_1",
                    models.CharField(
                        choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                        max_length=1,
                    ),
                ),
                (
                    "answer_2",
                    models.CharField(
                        choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                        max_length=1,
                    ),
                ),
                (
                    "confirm_check",
                    models.BooleanField(
                        default=False,
                        help_text="Hereby, I confirm that I am willingly submitting this ballot.",
                    ),
                ),
                (
                    "voter_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vt1500admin.voter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("s", "signup"),
                            ("l", "login"),
                            ("o", "logout"),
                            ("e", "createElection"),
                            ("v", "vote"),
                            ("y", "verify"),
                            ("x", "Reserved"),
                        ],
                        help_text="Authority Action Type",
                        max_length=1,
                    ),
                ),
                ("metadata", models.CharField(max_length=200)),
                ("action_datetime", models.DateTimeField()),
                (
                    "authority_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
