# Generated by Django 4.2.4 on 2023-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vt1500admin", "0002_alter_election_question_1_alter_election_question_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="answer_1",
            field=models.CharField(
                choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                default="b",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="answer_2",
            field=models.CharField(
                choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                default="b",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="question_1",
            field=models.TextField(
                default="Je mandate le Syndicat du personnel de bureau, des techniciens et des professionnels de l'administration du réseau de la santé et des services sociaux du Saguenay - Lac St-Jean - FSSS-CSN pour déclencher, au moment jugé opportun, une grève pouvant aller jusqu’à la grève générale illimitée (GGI). Que le déclenchement de la GGI soit précédé de séquences de grève, et ce, en tenant compte de la conjoncture de négociation."
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="question_2",
            field=models.TextField(
                default="Que le Syndicat du personnel de bureau, des techniciens et des professionnels de l'administration du réseau de la santé et des services sociaux du Saguenay - Lac St-Jean - FSSS-CSN procèdent à un vote de ralliement à l’adoption du mandat de grève par les syndicats affiliés à la Fédération de la santé et des services sociaux, selon les modalités applicables à la fédération."
            ),
        ),
    ]
