# Generated by Django 4.2.4 on 2023-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vt1500admin", "0003_alter_ballot_answer_1_alter_ballot_answer_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="vote",
            new_name="vote_1",
        ),
        migrations.AddField(
            model_name="voter",
            name="vote_2",
            field=models.CharField(
                blank=True,
                choices=[("b", "abstain"), ("f", "for"), ("a", "against")],
                max_length=1,
            ),
        ),
    ]
