# Generated by Django 4.2.4 on 2023-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vt1500admin",
            "0005_remove_election_results_pie_election_results_pie_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="question_2",
            field=models.TextField(
                default="Je mandate le syndicat du personnel de bureau, des techniciens et des professionnels de l'administration du réseau de la santé et des services sociaux du Saguenay - Lac St-Jean FSSS-CSN pour se rallier au mandat de grève obtenu par la majorité des syndicats concernés de la Fédération de la santé et des services sociaux – CSN."
            ),
        ),
    ]
