# Generated by Django 4.2.4 on 2023-09-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vt1500admin", "0006_alter_election_question_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionconfirm",
            name="agreement_check",
            field=models.BooleanField(
                default=False,
                help_text="Hereby, I accept and sign the License Agreement of UNIO voting application.",
            ),
        ),
    ]
