# Generated by Django 4.2.4 on 2023-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vt1500admin", "0007_alter_electionconfirm_agreement_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voted_at",
            field=models.DateTimeField(blank=True, default="2000-01-01 00:00"),
        ),
        migrations.AlterField(
            model_name="election",
            name="voting_end_datetime",
            field=models.DateTimeField(blank=True, default="2000-01-01 00:00"),
        ),
        migrations.AlterField(
            model_name="election",
            name="voting_start_datetime",
            field=models.DateTimeField(blank=True, default="2000-01-01 00:00"),
        ),
    ]
