# Generated by Django 4.2.5 on 2023-09-20 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt1500admin', '0011_alter_election_notice_interval_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='answer_1',
            field=models.CharField(choices=[('b', 'Abstention'), ('f', 'Pour'), ('a', 'Contre')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='answer_2',
            field=models.CharField(choices=[('b', 'Abstention'), ('f', 'Pour'), ('a', 'Contre')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='confirm_check',
            field=models.BooleanField(default=False, help_text='Par la présente, je confirme que je soumets volontiers ce bulletin de vote.'),
        ),
        migrations.AlterField(
            model_name='ballotcheck',
            name='cast_vote',
            field=models.CharField(blank=True, choices=[('b', 'Abstention'), ('f', 'Pour'), ('a', 'Contre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='election',
            name='notice_interval_hours',
            field=models.IntegerField(blank=True, default=24, validators=[django.core.validators.MinValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_1',
            field=models.CharField(blank=True, choices=[('b', 'Abstention'), ('f', 'Pour'), ('a', 'Contre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_2',
            field=models.CharField(blank=True, choices=[('b', 'Abstention'), ('f', 'Pour'), ('a', 'Contre')], max_length=1),
        ),
    ]
